"use client";

import React, { useState } from "react";

// Define the shape of our API response
interface ApiResponse {
  success: boolean;
  assetId?: string;
  imagePreview?: string;
  error?: string;
}

export default function ContentGenerationTab() {
  const [loading, setLoading] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [assetId, setAssetId] = useState<string | null>(null);

  // Form State
  const [brandName, setBrandName] = useState("Nike");
  const [description, setDescription] = useState("");

  const handleGenerate = async () => {
    if (!description) return alert("Please enter a description");

    setLoading(true);
    setGeneratedImage(null);
    setAssetId(null);

    try {
      // ---------------------------------------------------------
      // NOTE: Using the Mock/Real toggle here based on your setup
      // ---------------------------------------------------------
      const res = await fetch("/api/generate-asset", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ brandName, productDescription: description }),
      });

      const data = (await res.json()) as ApiResponse;

      if (!data.success) throw new Error(data.error || "Generation failed");

      setGeneratedImage(data.imagePreview!);
      setAssetId(data.assetId!);
    } catch (error: any) {
      console.error(error);
      alert(`Error: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleUploadToContentHub = () => {
    alert(
      `Initiating Upload Workflow for Asset ID: ${assetId || "NEW-ASSET"}...`
    );
    // Add your Sitecore upload logic here
  };

  const handleReset = () => {
    setGeneratedImage(null);
    setAssetId(null);
    setDescription("");
  };

  return (
    <div className="flex flex-col h-full bg-white">
      {/* Header Section (Always Visible for Context) */}
      <div className="px-4 py-4 border-b border-gray-100 bg-white sticky top-0 z-10">
        <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
          <span className="bg-violet-100 text-violet-600 p-1.5 rounded-lg">
            <svg
              className="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 10V3L4 14h7v7l9-11h-7z"
              />
            </svg>
          </span>
          AI Asset Studio
        </h2>
      </div>

      {/* SUCCESS STATE (Only shows when image is generated)                */}
      {generatedImage ? (
        <div className="flex-1 flex flex-col p-6 animate-in fade-in slide-in-from-bottom-8 duration-500 overflow-y-auto">
          {/* 2. Upload To Content Hub Component */}
          <div className="bg-gray-50 border border-gray-200 rounded-xl p-5 space-y-4">
            <div className="flex items-start gap-3">
              <div className="bg-green-100 p-2 rounded-full text-green-600 shrink-0">
                <svg
                  className="w-5 h-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M5 13l4 4L19 7"
                  />
                </svg>
              </div>
              <div>
                <h3 className="font-bold text-gray-900">
                  Asset Ready for Upload
                </h3>
                <p className="text-sm text-gray-500">
                  Review the asset above. If it meets brand guidelines, push it
                  directly to the DAM.
                </p>
                <div className="w-full relative rounded-2xl overflow-hidden shadow-2xl border border-gray-100 mb-6 group">
                  <img
                    src={generatedImage}
                    alt="AI Result"
                    className="w-full h-auto object-cover max-h-[400px]"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-4">
                    <span className="text-white text-xs font-mono bg-black/50 px-2 py-1 rounded">
                      Generated by Imagen
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex gap-3 pt-2">
              <button
                onClick={handleUploadToContentHub}
                className="flex-1 bg-gradient-to-tr from-violet-600 to-indigo-600 text-white font-semibold py-2.5 px-4 rounded-lg  transition-colors shadow-sm flex items-center justify-center gap-2"
              >
                <svg
                  className="w-4 h-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"
                  />
                </svg>
                Upload to Content Hub
              </button>

              <button
                onClick={handleReset}
                className="px-4 py-2.5 bg-white border border-gray-300 text-gray-700 font-medium rounded-lg hover:bg-gray-50 transition-colors"
              >
                Discard
              </button>
            </div>
          </div>
        </div>
      ) : (
        /* -------------------------------------------------------------------------- */
        /* VIEW 2: INPUT FORM (Shows when NO image exists)                            */
        /* -------------------------------------------------------------------------- */
        <>
          <div className="flex-1 overflow-y-auto p-4 space-y-6">
            {/* Step 1: Context */}
            <div className="space-y-3">
              <label className="text-sm font-semibold text-gray-700 block">
                1. Brand Context
              </label>
              <div className="relative">
                <select
                  className="w-full pl-3 pr-10 py-3 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all appearance-none"
                  value={brandName}
                  onChange={(e) => setBrandName(e.target.value)}
                  disabled={loading}
                >
                  <option value="Essential Living ">
                    Essential Living (Luxury, Energetic)
                  </option>
                  <option value="Skywings">Skywings (Travel, Earthy)</option>
                  <option value="Forma-lux ">Forma-lux (Retail, Clean)</option>
                  <option value="Nova-Medical">
                    Nova-Medical (Healthcare, Hospital)
                  </option>
                </select>
                <div className="absolute inset-y-0 right-0 flex items-center px-3 pointer-events-none text-gray-500">
                  <svg
                    className="w-4 h-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M19 9l-7 7-7-7"
                    />
                  </svg>
                </div>
              </div>
            </div>

            {/* Step 2: Prompt */}
            <div className="space-y-3">
              <label className="text-sm font-semibold text-gray-700 block">
                2. Product Vision
              </label>
              <textarea
                className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all min-h-[120px] resize-none"
                placeholder="Describe image you want to generate... "
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                disabled={loading}
              />
            </div>

            {/* Loading Animation (Shows WHILE loading, inside form area) */}
            {loading && (
              <div className="text-center p-8 w-full flex flex-col items-center justify-center animate-in fade-in duration-500">
                <div className="relative flex items-center justify-center w-24 h-24 mb-6">
                  <div className="absolute w-full h-full rounded-full bg-gradient-to-tr from-violet-200/40 to-blue-200/40 animate-pulse blur-xl"></div>
                  <div className="absolute w-20 h-20 border-2 border-indigo-100 rounded-full animate-[spin_4s_linear_infinite]"></div>
                  <div className="absolute w-20 h-20 border-t-[3px] border-l-[1px] border-transparent border-t-indigo-600 rounded-full animate-spin"></div>
                  <div className="relative w-12 h-12 rounded-full bg-gradient-to-tr from-violet-600 to-indigo-600 shadow-lg shadow-indigo-500/50 flex items-center justify-center animate-pulse">
                    <svg
                      className="w-6 h-6 text-white"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                      />
                    </svg>
                  </div>
                </div>
                <div className="space-y-3">
                  <h3 className="text-sm font-bold text-gray-900 tracking-tight">
                    AI Processing Initialized
                  </h3>
                  <p className="text-xs text-gray-500 font-medium px-4 leading-relaxed">
                    Opticore is dreaming up your image...
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Generate Button (Hidden when loading) */}
          {!loading && (
            <button
              onClick={handleGenerate}
              disabled={!description}
              className={`
                relative w-9/10 mx-auto block py-3 px-4 mb-4 rounded-xl font-bold text-sm tracking-widest uppercase transition-all duration-300 ease-out transform overflow-hidden group
                ${
                  !description
                    ? "bg-gray-100 text-gray-400 border border-gray-200 cursor-not-allowed"
                    : "bg-gradient-to-r from-violet-600 via-indigo-600 to-blue-600 text-white shadow-lg shadow-indigo-500/40 hover:shadow-indigo-500/60 hover:scale-[1.02] active:scale-[0.98] border border-indigo-500/30"
                }
              `}
            >
              <span className="relative z-10 flex items-center justify-center gap-2">
                <svg
                  className="w-4 h-4"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M13 10V3L4 14h7v7l9-11h-7z"
                  />
                </svg>
                Generate Asset
              </span>
            </button>
          )}
        </>
      )}
    </div>
  );
}
