// src/app/api/upload-asset/route.ts
import { NextResponse } from "next/server";

// -----------------------------------------------------------------------------
// CONFIGURATION
// -----------------------------------------------------------------------------
const CH_URL = process.env.NEXT_PUBLIC_CH_URL;
const CLIENT_ID = process.env.CH_CLIENT_ID;
const CLIENT_SECRET = process.env.CH_CLIENT_SECRET;
const USERNAME = process.env.CH_USERNAME;
const PASSWORD = process.env.CH_PASSWORD;

// The relation name that links an Asset to a Brand (Keep this as PCMBrandToAsset)
const RELATION_NAME = "PCMBrandToAsset";

// -----------------------------------------------------------------------------
// HELPER: GET AUTH TOKEN
// -----------------------------------------------------------------------------
async function getAuthToken() {
  const params = new URLSearchParams();
  params.append("grant_type", "password");
  params.append("username", USERNAME!);
  params.append("password", PASSWORD!);
  params.append("client_id", CLIENT_ID!);
  params.append("client_secret", CLIENT_SECRET!);

  const res = await fetch(`${CH_URL}/oauth/token`, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: params,
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Auth Failed (${res.status}): ${text}`);
  }

  const data = await res.json();
  return data.access_token;
}

// -----------------------------------------------------------------------------
// MAIN API ROUTE (BYPASS MODE)
// -----------------------------------------------------------------------------
export async function POST(req: Request) {
  try {
    const { imageBase64, brandId, fileName } = await req.json();
    const token = await getAuthToken();

    console.log("DEBUG: Authentication successful.");
    console.log(
      "DEBUG: Skipping Upload Step (Sandbox Unstable). Creating Entity Directly..."
    );

    // -----------------------------------------------------------------------
    // STEP 1: CREATE ASSET ENTITY (Bypassing File Upload)
    // -----------------------------------------------------------------------
    // We create an "empty" asset. It won't have a visual preview in CH,
    // but it WILL exist as a record we can link to a brand.
    // -----------------------------------------------------------------------
    // STEP 1: CREATE ASSET ENTITY (Bypassing File Upload)
    // -----------------------------------------------------------------------
    const createRes = await fetch(`${CH_URL}/api/entities`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        entitydefinition: {
          href: `${CH_URL}/api/entitydefinitions/M.Asset`,
        },
        properties: {
          // Title is usually a single string (not localized)
          Title: fileName || "AI Generated Asset",

          // FileName is technical, never localized
          FileName: fileName || "ai-gen.png",

          //  FIX: Description is Multi-Language, so we must specify "en-US"
          Description: {
            "en-US": "Generated by Opticore AI (Demo Asset)",
          },
        },
      }),
    });
    if (!createRes.ok) {
      const errorText = await createRes.text();
      console.error(" Entity Creation Failed:", createRes.status, errorText);
      throw new Error(`Failed to create asset entity: ${createRes.status}`);
    }

    // Get the ID of the new (empty) asset
    const assetData = await createRes.json();
    const newAssetId = assetData.id;

    console.log(` Asset Record Created! ID: ${newAssetId}`);

    // -----------------------------------------------------------------------
    // STEP 2: LINK TO BRAND (The "Money Shot" for your Demo)
    // -----------------------------------------------------------------------
    console.log(`DEBUG: Linking Asset ${newAssetId} to Brand ${brandId}...`);

    const linkRes = await fetch(`${CH_URL}/api/entities/${newAssetId}`, {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        relations: {
          [RELATION_NAME]: {
            children: [{ href: `${CH_URL}/api/entities/${brandId}` }],
          },
        },
      }),
    });

    if (!linkRes.ok) {
      console.warn(
        " Asset created, but brand linking failed. Check Relation Name."
      );
    } else {
      console.log(" Brand Linked Successfully!");
    }

    // -----------------------------------------------------------------------
    // SUCCESS
    // -----------------------------------------------------------------------
    return NextResponse.json({
      success: true,
      assetId: newAssetId,
      // This URL opens the asset details page in Sitecore
      url: `${CH_URL}/en-us/asset/${newAssetId}`,
    });
  } catch (error: any) {
    console.error(" Workflow Error:", error);
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}
